package com.whq.entity;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERID
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USERNAME
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.PASSWORD
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERID
     *
     * @return the value of USERINFO.USERID
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERID
     *
     * @param userid the value for USERINFO.USERID
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USERNAME
     *
     * @return the value of USERINFO.USERNAME
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USERNAME
     *
     * @param username the value for USERINFO.USERNAME
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.PASSWORD
     *
     * @return the value of USERINFO.PASSWORD
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.PASSWORD
     *
     * @param password the value for USERINFO.PASSWORD
     *
     * @mbggenerated Mon Apr 22 19:34:18 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}